### ISSUE TITLE
Redundant upgrade message.

### ISSUE THREAD

**Issue by aezur** [arashsheyda/nuxt-mongoose#14]
When building my project I get the message `A new version of Nuxt Mongoose (v0.0.9) is available: https://github.com/arashsheyda/nuxt-mongoose/releases/latest`.

I have v0.0.9 installed.

**Comment by arashsheyda** [comment]
Thank you for noticing this! I think the problem is that we first publish to npm and then bump the package's version, it will be fixed in the next version. thanks again

**Comment by arashsheyda** [comment]
sorry about that, I did the same mistake again :(

**Comment by lupus78** [comment]
I still see this issue. I have 1.0.5 installed but the error message is still present:

`A new version of Nuxt Mongoose (v1.0.5) is available: https://github.com/arashsheyda/nuxt-mongoose/releases/latest`

```
$ npm list | grep "nuxt-mongoose"
├── nuxt-mongoose@1.0.5
```

**Comment by arashsheyda** [comment]
@lupus78 thanks for notifying, but this happens when the module is published to npm before that the version is changed, I sometimes forget about it and then this happens.
