### ISSUE TITLE
Displaying data

### ISSUE THREAD

**Issue by R0N1n-dev** [arashsheyda/nuxt-mongoose#15]
![Screenshot from 2023-08-09 15-03-55](https://github.com/arashsheyda/nuxt-mongoose/assets/83344872/8daa3cae-778a-471a-8914-c2e77c100ac0)
![Screenshot from 2023-08-09 14-59-40](https://github.com/arashsheyda/nuxt-mongoose/assets/83344872/6abfad31-d5b7-4403-9377-c9b3551bb5a0)
![Screenshot from 2023-08-09 14-59-32](https://github.com/arashsheyda/nuxt-mongoose/assets/83344872/b4bcbc4d-56b3-451d-bece-69a52954015e)
![Screenshot from 2023-08-09 14-59-20](https://github.com/arashsheyda/nuxt-mongoose/assets/83344872/a993db14-a5ae-451c-a7d9-d4b6f7f9de91)
![Screenshot from 2023-08-09 15-00-28](https://github.com/arashsheyda/nuxt-mongoose/assets/83344872/a826afa0-c09a-41f9-89f4-70268733dce0)

Have installed the package and followed instructions but cant display data.
The dev tools query show no response. Whats going on coz i Have no errors but clearly am not getting any data from my database.
What is the right way to do this coz the documentation is scant

**Comment by arashsheyda** [comment]
@R0N1n-dev and also you can auto-import your models. the default folder for auto-import is `~/server/models` and you can change it from your `nuxt-config`, an example would be like:

```ts [nuxt-config]
export default defineNuxtConfig({
  devtools: { enabled: true },

  modules: [
    'nuxt-mongoose',
  ],

  mongoose: {
    uri: 'mongodb://127.0.0.1:27017/nuxt-mongoose',
    modelsDir: '../models', //here we are setting the modelsDir to `~/models`
  },
})
```

- `~` is your project's root directory
- the base of `modelsDir` auto-import is `~/server/`

**Comment by R0N1n-dev** [comment]
Ok, thats fixed but now i have no idea on how to add data coz my code is not working.
https://stackblitz.com/github/R0N1n-dev/nuxt-mongoose.
i get an error on post request

**Comment by R0N1n-dev** [comment]
Thank you

**Comment by R0N1n-dev** [comment]
Will do. I love mongodb and so this plugin will really help.
Good day
