### ISSUE TITLE
Stuck generating types in CLI

### ISSUE THREAD

**Issue by negativems** [arashsheyda/nuxt-mongoose#19]
**Nuxt gets stuck when generating types, and removing nuxt-mongoose fixes the issue.**

![image](https://github.com/arashsheyda/nuxt-mongoose/assets/20746840/9ee74cbb-7d7a-41b5-8c38-866e60b1b79c)

I tried:
- using npm instead of pnpm
- deleting node_modules and .nuxt
- Also tried it on a different computer with no success.

Additionally, I attempted to deploy it on Vercel and encountered the same issue.

I still face this problem even when removing all files that have the implementation of the module but the issue occurs only when I have it on nuxt.config.ts.

I also attempted to downgrade Nuxt from version 3.7.0 to 3.6.5, but this did not resolve the issue.

I found a similar issue here, and they suggested it might be related to the modules and not Nuxt itself:
https://github.com/nuxt/cli/issues/169

**Comment by mariagq777** [comment]
Me too... the same issue :(

**Comment by leaderit** [comment]
And me (

**Comment by arashsheyda** [comment]
Sorry I was away for a while and didn't have internet access :( It is probably caused by updates, and I'll try to fix it asap
