### ISSUE TITLE
published npm is different than build

### ISSUE THREAD

**Issue by arashsheyda** [arashsheyda/nuxt-mongoose#22]
after builded, when run npm publish the dist files changes and package is not working!

![image](https://github.com/arashsheyda/nuxt-mongoose/assets/38922203/f6409c5a-895f-45fe-9709-5c15a8ce92ef)

**Comment by BayBreezy** [comment]
Lol. That is weeeiirrdd... Now I cant use v1. I get this error that it cannot find the module

```bash
Error while requiring module nuxt-mongoose: Error: Cannot find module 'C:\Developer\Projects\nuxt-mongoose\node_modules\.pnpm\jiti@1.19.3\node_modules\jiti\lib\index.js'
```

I am not sure if pnpm is the issue here or some config that got updated

**Comment by arashsheyda** [comment]
@BayBreezy lol yes! no the issue is on my side. IDK why when publishing to npm, all the files are not publishing as you can see in the pic :(

**Comment by arashsheyda** [comment]
There was an `prepare` script which had `--stub` in it so when running `npm publish` it auto ran the `prepare` command and caused the problem. it is fixed now thanks to anthony!

**Comment by BayBreezy** [comment]
Awesome!
