### ISSUE TITLE
[Qestion] Get connect and make a writeable stream

### ISSUE THREAD

**Issue by maicss** [arashsheyda/nuxt-mongoose#34]
I need write some log to my mongodb, so how to get the connect cursor and make a writeable stream for my logger service?
Thanks advance!

**Comment by maicss** [comment]
Should I must use [defineMongooseConnection](https://nuxt-mongoose.nuxt.space/docs/api/utils#definemongooseconnection) to create a new connection ?

**Comment by arashsheyda** [comment]
@maicss you can use `import { connection } from 'mongoose'
