### ISSUE TITLE
Peer Dependency Conflicts in nuxt-mongoose

### ISSUE THREAD

**Issue by nicokempe** [arashsheyda/nuxt-mongoose#41]
Hello,

I'm encountering an issue with peer dependencies in `nuxt-mongoose` version 1.0.3, which is impacting our Nuxt 3 project. The issue was identified during our migration to `pnpm`.

### Environment
- Operating System: Windows_NT
- Node Version:     v20.8.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- User Config:      preset, experimental, devtools, modules, serverMiddleware, nitro, i18n, cloudflareAnalytics, turnstile, css, postcss, mongoose, app, runtimeConfig, routeRules, image, security, content, typescript
- Runtime Modules:  @nuxt/image@1.2.0, @nuxt/devtools@1.0.8, @nuxt/content@2.10.0, @nuxtjs/i18n@8.0.0, @nuxtjs/turnstile@0.6.3, @nuxtjs/tailwindcss@6.10.4, nuxt-security@1.0.0, nuxt-headlessui@1.1.5, nuxt-cloudflare-analytics@1.0.8

### Issue Description
There are several unmet peer dependency warnings in `nuxt-mongoose` and its subdependencies. Specifically, the issues are with `@nuxt/devtools`, `@unocss/nuxt`, `@unocss/vite`, `unocss`, and `@unocss/astro`, where the installed versions of these packages do not match the expected peer dependency versions.

Here are the details of the warnings:

1. `@nuxt/devtools-ui-kit 1.0.0` expects `@nuxt/devtools@1.0.0` but found `1.0.8`.
2. `@unocss/nuxt 0.56.5`, `@unocss/vite 0.56.5`, `unocss 0.56.5`, and `@unocss/astro 0.56.5` expect `vite@"^2.9.0 || ^3.0.0-0 || ^4.0.0"` but found `5.0.11`.

### Expected Behavior
The dependencies of `nuxt-mongoose` should be compatible with each other, without causing any peer dependency conflicts.

### Steps to Reproduce
1. Install `nuxt-mongoose` version 1.0.3 in a Nuxt 3 project using `pnpm`.
2. Observe the peer dependency warnings during installation.

### Logs
```
WARN  Issues with peer dependencies found
└─┬ nuxt-mongoose 1.0.3
  └─┬ @nuxt/devtools-ui-kit 1.0.0
    ├── ✕ unmet peer @nuxt/devtools@1.0.0: found 1.0.8
    ├─┬ @unocss/nuxt 0.56.5
    │ ├─┬ @unocss/vite 0.56.5
    │ │ └── ✕ unmet peer vite@"^2.9.0 || ^3.0.0-0 || ^4.0.0": found 5.0.11
    │ └─┬ unocss 0.56.5
    │   ├── ✕ unmet peer vite@"^2.9.0 || ^3.0.0-0 || ^4.0.0": found 5.0.11
    │   └─┬ @unocss/astro 0.56.5
    │     └── ✕ unmet peer vite@"^2.9.0 || ^3.0.0-0 || ^4.0.0": found 5.0.11
    └─┬ unocss 0.56.5
      └── ✕ unmet peer vite@"^2.9.0 || ^3.0.0-0 || ^4.0.0": found 5.0.11
```

Is there a plan to resolve these peer dependency conflicts in a future version of `nuxt-mongoose`? It would greatly help in maintaining the stability and compatibility of projects that rely on this package.

Thank you for your time and for maintaining `nuxt-mongoose`.

**Comment by arashsheyda** [comment]
will update them and make a release later today, thanks
