### ISSUE TITLE
Small problems with the new version

### ISSUE THREAD

**Issue by Ena-Heleneto** [arashsheyda/nuxt-mongoose#45]
When I upgraded the version to ^1.0.4, the console popped up an error

![image](https://github.com/arashsheyda/nuxt-mongoose/assets/69035266/8925c632-e01b-41a3-9bb1-7d688d5d9ef1)

please what should i do，thanks

**Comment by arashsheyda** [comment]
sorry about that, it is now fixed in the [latest version](https://www.npmjs.com/package/nuxt-mongoose/v/1.0.5)
