### ISSUE TITLE
Depreciation Warning Mongoose Strict Query

### ISSUE THREAD

**Issue by devniza** [arashsheyda/nuxt-mongoose#55]
I get the following warning error whenever my application connects to MongoDB via nuxt-mongoose. I am still able to connect and perform actions to the database, but I keep on getting this and I do not know how to disable it in the nuxt config.

How do I fix this error out of my log stream?
![image](https://github.com/arashsheyda/nuxt-mongoose/assets/115035737/6e59baed-e594-45b3-9956-5f9114c576c0)

Nuxt Config 
![image](https://github.com/arashsheyda/nuxt-mongoose/assets/115035737/844f2cac-91cd-438d-b6e4-278c46566647)

`[MONGOOSE] DeprecationWarning: Mongoose: the strictQuery option will be switched back to false by default in Mongoose 7. Use mongoose.set('strictQuery', false); if you want to prepare for this change. Or use mongoose.set('strictQuery', true); to suppress this warning.
(Use node --trace-deprecation ... to show where the warning was created)`

**Comment by arashsheyda** [comment]
@devniza can you share a small reproduction? (we are using mongoose 8 and I'm not sure why are you getting this warning)

**Comment by devniza** [comment]
Hi, apologies for the late response.
I managed to fix the error by simply running `pnpm i mongoose` to update it to the latest version.
