### ISSUE TITLE
How to create Discriminators

### ISSUE THREAD

**Issue by RodrigoRoy** [arashsheyda/nuxt-mongoose#56]
I just learned how to use [Discriminators](https://mongoosejs.com/docs/discriminators.html) and I think it has great potential. I checked the pull request "[add discriminators.ts helper](https://github.com/arashsheyda/nuxt-mongoose/pull/47)" by @jbool24 about this issue, but I think it's still unavailable in the API to create discriminators.

Any plans to implement it or sugestions about this topic? Thanks a lot for NuxtMongoose, I really appretiate the effort of all the people involved.

**Comment by arashsheyda** [comment]
added in #47
