### ISSUE TITLE
Cannot add mongoose option to the config file

### ISSUE THREAD

**Issue by bigbean17** [arashsheyda/nuxt-mongoose#59]
Hi,

I'm trying to add mongoose to the config file, but I'm keep getting this error
<img width="780" alt="image" src="https://github.com/arashsheyda/nuxt-mongoose/assets/69971426/626b45da-57b2-4258-92ef-0d5988e45670">
Here is the config file
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxt/ui", "nuxt-mongoose"],
  css: ['~/assets/css/main.css'],
  mongoose:{
    
  }
})
```
Does anyone know how can I fix this? Any help would be appreciated. 

Thanks!

**Comment by arashsheyda** [comment]
@bigbean17 for me usually when I just install the module and try to add `mongoose` config to `nuxt.config`, it doesn't recognized it; but when I run the `dev` script it works. or it might be something with your IDE, if you could share a minimal reproduction we could investigate it better. thanks
