### ISSUE TITLE
Unique isn't erroring

### ISSUE THREAD

**Issue by sell** [arashsheyda/nuxt-mongoose#7]
With unique set to true documents with same value are being duped. 
<img width="417" alt="image" src="https://github.com/arashsheyda/nuxt-mongoose/assets/34258275/b3eaa5c8-aeb3-41d4-95ba-bc8dc880a2c6">

<img width="417" alt="image" src="https://github.com/arashsheyda/nuxt-mongoose/assets/34258275/7f7dc317-6011-479e-bd0b-45a67fba21f0">

**Comment by arashsheyda** [comment]
@sell Can you help to provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thanks.

Here is a minimal [project](https://github.com/arashsheyda/nuxt-mongoose-minimal) of mine for example, and the unique erroring is working there somehow.

thank you

**Comment by sell** [comment]
The solution was dropping the database and recreating it. I suppose since I stored a document then update the unique key to true afterwards it didn't kick in. Appreciate the quick response, good wrapper you have here for nuxt!

**Comment by arashsheyda** [comment]
@sell thank you, It's so heart warming
